In [8]:
# We are using Content Based Recommenation System
import pandas as pd

In [9]:
movies = pd.read_csv('movies.csv')
credits = pd.read_csv('credits.csv')

In [10]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",10-12-2009,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",19-05-2007,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [11]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [12]:
# To check the data of the column
credits.head()['cast'].values

array(['[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]',
       '[{"cast_id": 4, "character": "Captain Jack Sparrow", "credit_id": "52fe4232c3a36847f800b50d", "gender": 2, "id": 85, "name": "Johnny Depp", "order": 0}, {"cast_id": 5, "character": "Will Turner", "credit_id": "52fe4232c3a36847f800b511", "gender": 2, "id": 114, "name": "Orlando Bloom", "order": 1}, {"cast_id": 6, "character": "Elizabeth Swann", "credit_id": "52fe4232c3a36847f800b515", "gender": 1, "id": 116, "name": "Keira Knightley", "order": 2}, {"cast_id": 12, "character": "William \\"Bootstrap Bill\\" Turner", "credit_id": "52fe4232c3a36847f800b52d", "gender": 2, "id": 1640, "name": "Stellan Skarsg\\u00e5rd", "order": 3}, {"cast_id": 10, "character": "Captain Sao Feng", "credit_id": "52fe4232c3a36847f800b525", "gender": 2, "id": 1619, "name": "Chow Yun-fat", "order": 4}, {"cast_id": 9, "character": "Captain Davy Jones", "credit_id": "52fe4232c3a36847f800b521", "gender": 2, "id": 2440, "name": "Bill Nighy", "order": 5}, {"cast_id": 7, "character": "Captain Hector Barbossa", "credit_id": "52fe4232c3a36847f800b519", "gender": 2, "id": 118, "name": "Geoffrey Rush", "order": 6}, {"cast_id": 14, "character": "Admiral James Norrington", "credit_id": "52fe4232c3a36847f800b535", "gender": 2, "id": 1709, "name": "Jack Davenport", "order": 7}, {"cast_id": 13, "character": "Joshamee Gibbs", "credit_id": "52fe4232c3a36847f800b531", "gender": 2, "id": 2449, "name": "Kevin McNally", "order": 8}, {"cast_id": 11, "character": "Lord Cutler Beckett", "credit_id": "52fe4232c3a36847f800b529", "gender": 2, "id": 2441, "name": "Tom Hollander", "order": 9}, {"cast_id": 19, "character": "Tia Dalma", "credit_id": "52fe4232c3a36847f800b549", "gender": 1, "id": 2038, "name": "Naomie Harris", "order": 10}, {"cast_id": 8, "character": "Governor Weatherby Swann", "credit_id": "52fe4232c3a36847f800b51d", "gender": 2, "id": 378, "name": "Jonathan Pryce", "order": 11}, {"cast_id": 37, "character": "Captain Teague Sparrow", "credit_id": "52fe4232c3a36847f800b5b3", "gender": 2, "id": 1430, "name": "Keith Richards", "order": 12}, {"cast_id": 16, "character": "Pintel", "credit_id": "52fe4232c3a36847f800b53d", "gender": 2, "id": 1710, "name": "Lee Arenberg", "order": 13}, {"cast_id": 15, "character": "Ragetti", "credit_id": "52fe4232c3a36847f800b539", "gender": 2, "id": 1711, "name": "Mackenzie Crook", "order": 14}, {"cast_id": 18, "character": "Lieutenant Theodore Groves", "credit_id": "52fe4232c3a36847f800b545", "gender": 2, "id": 4031, "name": "Greg Ellis", "order": 15}, {"cast_id": 55, "character": "Cotton", "credit_id": "57e28d2ec3a3681a01005b5c", "gender": 2, "id": 1715, "name": "David Bailie", "order": 16}, {"cast_id": 17, "character": "Marty", "credit_id": "52fe4232c3a36847f800b541", "gender": 2, "id": 4030, "name": "Martin Klebba", "order": 17}, {"cast_id": 57, "character": "Ian Mercer", "credit_id": "57e28d78c3a36808b900bf4f", "gender": 0, "id": 939, "name": "David Schofield", "order": 18}, {"cast_id": 62, "character": "Scarlett", "credit_id": "57e28ec5c3a3681a50005855", "gender": 1, "id": 2450, "name": "Lauren Maher", "order": 19}, {"cast_id": 63, "character": "Giselle", "credit_id": "57e28ed692514123f5005635", "gender": 1, "id": 2452, "name": "Vanessa Branch", "order": 20}, {"cast_id": 60, "character": "Mullroy", "credit_id": "57e28db2c3a3681a01005bc7", "gender": 2, "id": 1714, "name": "Angus Barnett", "order": 21}, {"cast_id": 59, "character": "Murtogg", "credit_id": "57e28da192514118f7006008", "gender": 0, "id": 1713, "name": "Giles New", "order": 22}, {"cast_id": 58, "character": "Tai Huang", "credit_id": "57e28d8ec3a3681a01005bab", "gender": 2, "id": 22075, "name": "Reggie Lee", "order": 23}, {"cast_id": 64, "character": "Henry Turner", "credit_id": "57e29119925141151100a6cc", "gender": 2, "id": 61259, "name": "Dominic Scott Kay", "order": 24}, {"cast_id": 39, "character": "Mistress Ching", "credit_id": "52fe4232c3a36847f800b5bd", "gender": 1, "id": 33500, "name": "Takayo Fischer", "order": 25}, {"cast_id": 40, "character": "Lieutenant Greitzer", "credit_id": "52fe4232c3a36847f800b5c1", "gender": 2, "id": 1224149, "name": "David Meunier", "order": 26}, {"cast_id": 49, "character": "Hadras", "credit_id": "56d1871c92514174680010cf", "gender": 2, "id": 429401, "name": "Ho-Kwan Tse", "order": 27}, {"cast_id": 56, "character": "Clacker", "credit_id": "57e28d4b92514125710055cb", "gender": 0, "id": 1123, "name": "Andy Beckwith", "order": 28}, {"cast_id": 51, "character": "Penrod", "credit_id": "56ec8c14c3a3682260003c53", "gender": 2, "id": 1056117, "name": "Peter Donald Badalamenti II", "order": 29}, {"cast_id": 61, "character": "Cotton\'s Parrot (voice)", "credit_id": "57e28dcc9251412463005678", "gender": 2, "id": 21700, "name": "Christopher S. Capp", "order": 30}, {"cast_id": 65, "character": "Captain Teague", "credit_id": "58bc2a37c3a368663003740b", "gender": 2, "id": 1430, "name": "Keith Richards", "order": 31}, {"cast_id": 66, "character": "Captain Jocard", "credit_id": "58bc2a8e925141609e03a179", "gender": 2, "id": 2603, "name": "Hakeem Kae-Kazim", "order": 32}, {"cast_id": 67, "character": "Captain Ammand", "credit_id": "58e2a21ac3a36872af00f9c2", "gender": 0, "id": 70577, "name": "Ghassan Massoud", "order": 33}]',

In [13]:
# To merge the data frames
movies.merge(credits, on = 'title')

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4803,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4804,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4805,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4806,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4807,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [14]:
movies.shape

(4803, 20)

In [15]:
credits.shape

(4803, 4)

In [16]:
movies = movies.merge(credits, on = 'title')

In [17]:
movies.shape

(4808, 23)

In [18]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [19]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4808 entries, 0 to 4807
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4808 non-null   int64
 1   genres                4808 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4808 non-null   int64
 4   keywords              4808 non-null   object
 5   original_language     4808 non-null   object
 6   original_title        4808 non-null   object
 7   overview              4805 non-null   object
 8   popularity            4808 non-null   float64
 9   production_companies  4808 non-null   object
 10  production_countries  4808 non-null   object
 11  release_date          4807 non-null   object
 12  revenue               4808 non-null   int64
 13  runtime               4806 non-null   float64
 14  spoken_languages      4808 non-null   object
 15  status                4808 non-null   object
 16  tagline               3964 non-null   object
 17  title                 4808 non-null   object
 18  vote_average          4808 non-null   float64
 19  vote_count            4808 non-null   int64
 20  movie_id              4808 non-null   int64
 21  cast                  4808 non-null   object
 22  crew                  4808 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.1+ KB

In [20]:
movies['original_language'].value_counts
# if we drop movie no major differs will be made as high count of english movies

<bound method IndexOpsMixin.value_counts of 0       en
1       en
2       en
3       en
4       en
        ..
4803    es
4804    en
4805    en
4806    en
4807    en
Name: original_language, Length: 4808, dtype: object>

In [21]:
# Specify the columns to drop
columns_to_drop = ['budget', 'homepage', 'original_title', 'popularity', 'production_companies',
                   'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages',
                   'status', 'tagline', 'vote_average', 'vote_count', 'id', 'original_language']

# Drop the specified columns using inplace=True
movies.drop(columns=columns_to_drop, axis=1, inplace=True)

In [22]:
# genres
# keywords
# title
# overview
# cast
# crew
# movie_id

In [23]:
movies.head()
#main data

,genres,keywords,overview,title,movie_id,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,Spectre,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Dark Knight Rises,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",John Carter,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [24]:
movies.isnull().sum()

genres      0
keywords    0
overview    3
title       0
movie_id    0
cast        0
crew        0
dtype: int64

In [25]:
#Dropping the null values
movies.dropna(inplace=True)

In [26]:
#Checking the null values of the Dataframe
movies.isnull().sum()

genres      0
keywords    0
overview    0
title       0
movie_id    0
cast        0
crew        0
dtype: int64

In [27]:
# Checking if there are any duplicate values
movies.duplicated().sum()

0

In [28]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [29]:
#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
#['Action', 'Adventure', 'Fantasy', 'SciFi']

In [30]:
import ast

In [31]:
# Hepler function
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [32]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,genres,keywords,overview,title,movie_id,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,Spectre,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Dark Knight Rises,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",John Carter,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [33]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,genres,keywords,overview,title,movie_id,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,Spectre,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [34]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [35]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,genres,keywords,overview,title,movie_id,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,19995,"[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,285,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,Spectre,206647,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,49026,"[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter,49529,"[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [36]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [37]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [38]:
movies.sample(5)

,genres,keywords,overview,title,movie_id,cast,crew
226,"[Comedy, Drama, Romance]","[love triangle, baseball, athlete, aftercredit...",After being cut from the USA softball team and...,How Do You Know,42888,"[Reese Witherspoon, Paul Rudd, Owen Wilson, Ja...",[James L. Brooks]
4089,[Drama],"[suicide, gambling, manager, alcohol, based on...",Fast Eddie Felson is a small-time pool hustler...,The Hustler,990,"[Paul Newman, Jackie Gleason, Piper Laurie, Ge...",[Robert Rossen]
1678,"[Adventure, Drama, Action, History, War]","[martial arts, sword, revolution, blood, gunfi...","At the beginning of the 20th century, China is...",1911,76349,"[Jackie Chan, Li Bingbing, Joan Chen, Jaycee C...","[Jackie Chan, 张立 | Zhang Li]"
3982,"[Crime, Action]",[],A rogue soldier turned outlaw is thrust into a...,Close Range,325173,"[Scott Adkins, Nick Chinlund, Caitlin Keats, J...",[Isaac Florentine]
3365,[Horror],"[upper class, halloween, psychopath, urban leg...",Two teenage couples traveling across the backw...,House of 1000 Corpses,2662,"[Sid Haig, Bill Moseley, Sheri Moon Zombie, Ka...",[Rob Zombie]

In [39]:
'Sam Rockwell'
'SamRockwell'

'SamRockwell'

In [40]:
# To transform
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [41]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [42]:
movies.head()

,genres,keywords,overview,title,movie_id,cast,crew
0,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","In the 22nd century, a paraplegic Marine is di...",Avatar,19995,"[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,285,"[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",A cryptic message from Bond’s past sends him o...,Spectre,206647,"[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",Following the death of District Attorney Harve...,The Dark Knight Rises,49026,"[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","John Carter is a war-weary, former military ca...",John Carter,49529,"[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [43]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [44]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [45]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])
new.head()

,title,movie_id,tags
0,Avatar,19995,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,Pirates of the Caribbean: At World's End,285,"[Captain, Barbossa,, long, believed, to, be, d..."
2,Spectre,206647,"[A, cryptic, message, from, Bond’s, past, send..."
3,The Dark Knight Rises,49026,"[Following, the, death, of, District, Attorney..."
4,John Carter,49529,"[John, Carter, is, a, war-weary,, former, mili..."

In [46]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,title,movie_id,tags
0,Avatar,19995,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,285,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,206647,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,49026,Following the death of District Attorney Harve...
4,John Carter,49529,"John Carter is a war-weary, former military ca..."

In [47]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [48]:
vector = cv.fit_transform(new['tags']).toarray()

In [49]:
vector.shape

(4805, 5000)

In [50]:
from sklearn.metrics.pairwise import cosine_similarity

In [51]:
similarity = cosine_similarity(vector)

In [52]:
similarity

array([[1.        , 0.07142857, 0.05143445, ..., 0.02353104, 0.02571722,
        0.        ],
       [0.07142857, 1.        , 0.07715167, ..., 0.02353104, 0.        ,
        0.        ],
       [0.05143445, 0.07715167, 1.        , ..., 0.02541643, 0.        ,
        0.        ],
       ...,
       [0.02353104, 0.02353104, 0.02541643, ..., 1.        , 0.07624929,
        0.05083286],
       [0.02571722, 0.        , 0.        , ..., 0.07624929, 1.        ,
        0.05555556],
       [0.        , 0.        , 0.        , ..., 0.05083286, 0.05555556,
        1.        ]])

In [53]:
# To find the index of the movie
new[new['title'] == 'The Lego Movie'].index[0]

744

In [56]:
# enumerate is used to covert similarity of each movie in list 
sorted(list(enumerate(similarity[0])))

[(0, 1.0),
 (1, 0.07142857142857144),
 (2, 0.05143444998736397),
 (3, 0.03308611113236434),
 (4, 0.16101529717988267),
 (5, 0.09156219276643894),
 (6, 0.020088585092257697),
 (7, 0.13829563644637993),
 (8, 0.04761904761904762),
 (9, 0.05878963512522154),
 (10, 0.10286889997472794),
 (11, 0.07229440390678199),
 (12, 0.07715167498104596),
 (13, 0.03919309008348103),
 (14, 0.09412416106700235),
 (15, 0.044543540318737404),
 (16, 0.06419407387663695),
 (17, 0.130031582934249),
 (18, 0.10044292546128848),
 (19, 0.07655590023509529),
 (20, 0.051434449987363975),
 (21, 0.07715167498104596),
 (22, 0.059391387091649865),
 (23, 0.07824607964359516),
 (24, 0.04941662111074008),
 (25, 0.032712244767539374),
 (26, 0.13093073414159542),
 (27, 0.16645007571529583),
 (28, 0.10585122480499262),
 (29, 0.06419407387663695),
 (30, 0.05832118435198042),
 (31, 0.12858612496840993),
 (32, 0.07655590023509529),
 (33, 0.07715167498104596),
 (34, 0.0),
 (35, 0.07938841860374446),
 (36, 0.1860968420796942),
 (37, 0.07059312080025176),
 (38, 0.05381220025006314),
 (39, 0.07229440390678199),
 (40, 0.04239039033992974),
 (41, 0.12598815766974242),
 (42, 0.0),
 (43, 0.10910894511799618),
 (44, 0.060522753266880246),
 (45, 0.08559209850218259),
 (46, 0.15275252316519466),
 (47, 0.17699808135119713),
 (48, 0.05926955847701998),
 (49, 0.05455447255899809),
 (50, 0.11085479909473867),
 (51, 0.07715167498104596),
 (52, 0.10699012312772824),
 (53, 0.07142857142857144),
 (54, 0.05730682550612528),
 (55, 0.06944193284588147),
 (56, 0.14085904245475275),
 (57, 0.04819626927118799),
 (58, 0.041239304942116126),
 (59, 0.07597371763975863),
 (60, 0.025031308716087945),
 (61, 0.1889822365046136),
 (62, 0.06299407883487121),
 (63, 0.0777615791359739),
 (64, 0.02470831055537004),
 (65, 0.017817416127494958),
 (66, 0.022750787759664503),
 (67, 0.13226001425322162),
 (68, 0.09883324222148016),
 (69, 0.045175395145262566),
 (70, 0.07319250547113999),
 (71, 0.07412493166611012),
 (72, 0.09523809523809525),
 (73, 0.027713699773684666),
 (74, 0.20935894733965593),
 (75, 0.08058229640253804),
 (76, 0.06613000712661082),
 (77, 0.012858612496840992),
 (78, 0.044543540318737404),
 (79, 0.060783067385483086),
 (80, 0.030407921687296068),
 (81, 0.10482848367219183),
 (82, 0.06978631577988531),
 (83, 0.20256711147285467),
 (84, 0.13195808169029696),
 (85, 0.09212254307176114),
 (86, 0.06613000712661082),
 (87, 0.10286889997472794),
 (88, 0.10286889997472794),
 (89, 0.05292561240249631),
 (90, 0.060522753266880246),
 (91, 0.13231403100624078),
 (92, 0.08247860988423225),
 (93, 0.04761904761904762),
 (94, 0.11501092655705904),
 (95, 0.10699012312772824),
 (96, 0.07715167498104596),
 (97, 0.07412493166611012),
 (98, 0.07412493166611012),
 (99, 0.048795003647426664),
 (100, 0.05455447255899809),
 (101, 0.06752237049095156),
 (102, 0.10130511230913847),
 (103, 0.07902607796935997),
 (104, 0.05542739954736933),
 (105, 0.07229440390678199),
 (106, 0.036119682191538494),
 (107, 0.0839921051131616),
 (108, 0.1469861839480328),
 (109, 0.06734350297014739),
 (110, 0.018712029714127994),
 (111, 0.11765520133375293),
 (112, 0.07824607964359516),
 (113, 0.041612518928823956),
 (114, 0.041612518928823956),
 (115, 0.048795003647426664),
 (116, 0.050734628943184104),
 (117, 0.05372153093502536),
 (118, 0.015748519708717802),
 (119, 0.0419960525565808),
 (120, 0.0),
 (121, 0.06752237049095156),
 (122, 0.09883324222148016),
 (123, 0.11021667854435135),
 (124, 0.05832118435198042),
 (125, 0.07493633116627257),
 (126, 0.09002982732126874),
 (127, 0.123898656945838),
 (128, 0.0),
 (129, 0.08642716314028857),
 (130, 0.02686076546751268),
 (131, 0.09523809523809525),
 (132, 0.06752237049095156),
 (133, 0.029695693545824933),
 (134, 0.10910894511799618),
 (135, 0.0),
 (136, 0.020806259464411978),
 (137, 0.030116930096841712),
 (138, 0.07142857142857144),
 (139, 0.13397282541141675),
 (140, 0.044086671417740544),
 (141, 0.10350983390135313),
 (142, 0.08451542547285165),
 (143, 0.06241877839323594),
 (144, 0.044543540318737404),
 (145, 0.01928791874526149),
 (146, 0.015203960843648034),
 (147, 0.05455447255899809),
 (148, 0.10585122480499262),
 (149, 0.13977131156292244),
 (150, 0.16718346377260584),
 (151, 0.17251638983558856),
 (152, 0.048795003647426664),
 (153, 0.09569487529386911),
 (154, 0.029695693545824933),
 (155, 0.0),
 (156, 0.060265755276773095),
 (157, 0.12104550653376049),
 (158, 0.15936381457791915),
 (159, 0.048795003647426664),
 (160, 0.10286889997472794),
 (161, 0.029695693545824933),
 (162, 0.03217447260438935),
 (163, 0.046524210519923545),
 (164, 0.08183170883849714),
 (165, 0.04501491366063437),
 (166, 0.10012523486435178),
 (167, 0.08596023825918792),
 (168, 0.13957263155977065),
 (169, 0.09960238411119947),
 (170, 0.07968190728895957),
 (171, 0.027713699773684666),
 (172, 0.11664236870396086),
 (173, 0.020619652471058063),
 (174, 0.09412416106700235),
 (175, 0.046524210519923545),
 (176, 0.027713699773684666),
 (177, 0.029695693545824933),
 (178, 0.02182178902359924),
 (179, 0.059391387091649865),
 (180, 0.019920476822239894),
 (181, 0.020437977982832194),
 (182, 0.08642716314028857),
 (183, 0.06617222226472869),
 (184, 0.17078251276599332),
 (185, 0.07229440390678199),
 (186, 0.03539961627023943),
 (187, 0.11631052629980887),
 (188, 0.040177170184515394),
 (189, 0.06299407883487121),
 (190, 0.07174960033341753),
 (191, 0.0419960525565808),
 (192, 0.0),
 (193, 0.09878259746169996),
 (194, 0.0),
 (195, 0.050734628943184104),
 (196, 0.04501491366063437),
 (197, 0.0419960525565808),
 (198, 0.050734628943184104),
 (199, 0.11853911695403994),
 (200, 0.059391387091649865),
 (201, 0.0),
 (202, 0.02817180849095055),
 (203, 0.09759000729485333),
 (204, 0.04706208053350117),
 (205, 0.06900655593423542),
 (206, 0.1259881576697424),
 (207, 0.07824607964359516),
 (208, 0.14969623771302396),
 (209, 0.02865341275306264),
 (210, 0.04761904761904762),
 (211, 0.023531040266750586),
 (212, 0.07059312080025176),
 (213, 0.09720197391996738),
 (214, 0.07610194341477616),
 (215, 0.06419407387663695),
 (216, 0.059391387091649865),
 (217, 0.04239039033992974),
 (218, 0.029160592175990215),
 (219, 0.048795003647426664),
 (220, 0.16366341767699427),
 (221, 0.022271770159368702),
 (222, 0.0839921051131616),
 (223, 0.07319250547113999),
 (224, 0.05493731565986336),
 (225, 0.046004370622823615),
 (226, 0.025367314471592052),
 (227, 0.07824607964359516),
 (228, 0.11375393879832252),
 (229, 0.06944193284588147),
 (230, 0.07838618016696206),
 (231, 0.0),
 (232, 0.10744306187005072),
 (233, 0.083141099321054),
 (234, 0.06241877839323594),
 (235, 0.05542739954736933),
 (236, 0.07938841860374446),
 (237, 0.05832118435198043),
 (238, 0.11396057645963795),
 (239, 0.10309826235529032),
 (240, 0.048795003647426664),
 (241, 0.07824607964359516),
 (242, 0.07715167498104596),
 (243, 0.0839921051131616),
 (244, 0.0563436169819011),
 (245, 0.07509392614826384),
 (246, 0.05878963512522154),
 (247, 0.0),
 (248, 0.04239039033992974),
 (249, 0.11461365101225056),
 (250, 0.0),
 (251, 0.033671751485073696),
 (252, 0.020437977982832194),
 (253, 0.08559209850218259),
 (254, 0.06752237049095156),
 (255, 0.025031308716087945),
 (256, 0.06172133998483677),
 (257, 0.08908708063747481),
 (258, 0.01928791874526149),
 (259, 0.05372153093502536),
 (260, 0.21170244960998524),
 (261, 0.02182178902359924),
 (262, 0.06241877839323594),
 (263, 0.08058229640253804),
 (264, 0.0),
 (265, 0.027277236279499045),
 (266, 0.09883324222148016),
 (267, 0.059391387091649865),
 (268, 0.022750787759664503),
 (269, 0.026462806201248155),
 (270, 0.11021667854435137),
 (271, 0.07938841860374446),
 (272, 0.02817180849095055),
 (273, 0.03984095364447979),
 (274, 0.07458533939516852),
 (275, 0.10286889997472794),
 (276, 0.048795003647426664),
 (277, 0.05832118435198042),
 (278, 0.08908708063747481),
 (279, 0.08817334283548109),
 (280, 0.045501575519329006),
 (281, 0.05698028822981897),
 (282, 0.02686076546751268),
 (283, 0.0),
 (284, 0.01885115452718528),
 (285, 0.018993429409939658),
 (286, 0.019440394783993474),
 (287, 0.01928791874526149),
 (288, 0.0),
 (289, 0.044543540318737404),
 (290, 0.05542739954736933),
 (291, 0.04761904761904762),
 (292, 0.08596023825918792),
 (293, 0.025717224993681984),
 (294, 0.10286889997472794),
 (295, 0.09412416106700233),
 (296, 0.037151880838356854),
 (297, 0.044086671417740544),
 (298, 0.0),
 (299, 0.0363696483726654),
 (300, 0.1559023911155809),
 (301, 0.16143660075018942),
 (302, 0.05143444998736397),
 (303, 0.025367314471592052),
 (304, 0.06506000486323554),
 (305, 0.1648119469795901),
 (306, 0.08451542547285165),
 (307, 0.09212254307176114),
 (308, 0.05832118435198043),
 (309, 0.05730682550612528),
 (310, 0.03347309635022892),
 (311, 0.13226001425322162),
 (312, 0.09759000729485333),
 (313, 0.07484811885651198),
 (314, 0.0),
 (315, 0.083141099321054),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.059391387091649865),
 (320, 0.026082026547865053),
 (321, 0.0),
 (322, 0.1904761904761905),
 (323, 0.02817180849095055),
 (324, 0.024098134635593994),
 (325, 0.07938841860374446),
 (326, 0.048795003647426664),
 (327, 0.026462806201248155),
 (328, 0.0),
 (329, 0.06546536707079771),
 (330, 0.08908708063747481),
 (331, 0.045501575519329006),
 (332, 0.13231403100624078),
 (333, 0.026082026547865053),
 (334, 0.09412416106700235),
 (335, 0.04941662111074008),
 (336, 0.060522753266880246),
 (337, 0.022271770159368702),
 (338, 0.0),
 (339, 0.04819626927118799),
 (340, 0.04761904761904762),
 (341, 0.05143444998736397),
 (342, 0.12309149097933272),
 (343, 0.019596545041740514),
 (344, 0.05292561240249631),
 (345, 0.02119519516996487),
 (346, 0.0),
 (347, 0.0),
 (348, 0.05372153093502536),
 (349, 0.08058229640253804),
 (350, 0.04706208053350117),
 (351, 0.0),
 (352, 0.025367314471592052),
 (353, 0.019596545041740514),
 (354, 0.0),
 (355, 0.03888078956798695),
 (356, 0.08451542547285165),
 (357, 0.0),
 (358, 0.05730682550612528),
 (359, 0.029160592175990215),
 (360, 0.0),
 (361, 0.04706208053350117),
 (362, 0.07229440390678199),
 (363, 0.0777615791359739),
 (364, 0.02182178902359924),
 (365, 0.06419407387663695),
 (366, 0.05455447255899809),
 (367, 0.0),
 (368, 0.11878277418329973),
 (369, 0.08596023825918792),
 (370, 0.046004370622823615),
 (371, 0.09304842103984709),
 (372, 0.048795003647426664),
 (373, 0.15130688316720062),
 (374, 0.03827795011754764),
 (375, 0.03827795011754764),
 (376, 0.0419960525565808),
 (377, 0.0),
 (378, 0.0),
 (379, 0.05655346358155584),
 (380, 0.024098134635593994),
 (381, 0.07079923254047886),
 (382, 0.0),
 (383, 0.048795003647426664),
 (384, 0.06734350297014739),
 (385, 0.0),
 (386, 0.020619652471058063),
 (387, 0.022750787759664503),
 (388, 0.0),
 (389, 0.08596023825918792),
 (390, 0.022750787759664503),
 (391, 0.05613608914238398),
 (392, 0.02686076546751268),
 (393, 0.0),
 (394, 0.022271770159368702),
 (395, 0.04706208053350117),
 (396, 0.018312438553287787),
 (397, 0.048795003647426664),
 (398, 0.0),
 (399, 0.04501491366063437),
 (400, 0.08596023825918792),
 (401, 0.02817180849095055),
 (402, 0.050734628943184104),
 (403, 0.09221388919541469),
 (404, 0.05730682550612528),
 (405, 0.026462806201248155),
 (406, 0.018575940419178427),
 (407, 0.04501491366063437),
 (408, 0.029695693545824933),
 (409, 0.0),
 (410, 0.09100315103865801),
 (411, 0.045501575519329006),
 (412, 0.08817334283548109),
 (413, 0.1235415527768502),
 (414, 0.029695693545824933),
 (415, 0.07377111135633176),
 (416, 0.04706208053350117),
 (417, 0.027713699773684666),
 (418, 0.027713699773684666),
 (419, 0.06546536707079771),
 (420, 0.11375393879832252),
 (421, 0.0),
 (422, 0.12598815766974242),
 (423, 0.045501575519329006),
 (424, 0.03587480016670876),
 (425, 0.10403129732205989),
 (426, 0.05532833351724882),
 (427, 0.02686076546751268),
 (428, 0.054554472558998104),
 (429, 0.0),
 (430, 0.04706208053350117),
 (431, 0.022043335708870272),
 (432, 0.1113588507968435),
 (433, 0.025717224993681984),
 (434, 0.0),
 (435, 0.03217447260438935),
 (436, 0.0),
 (437, 0.02470831055537004),
 (438, 0.025031308716087945),
 (439, 0.025031308716087945),
 (440, 0.024397501823713332),
 (441, 0.025367314471592052),
 (442, 0.04239039033992974),
 (443, 0.046524210519923545),
 (444, 0.0),
 (445, 0.023531040266750586),
 (446, 0.022271770159368702),
 (447, 0.02119519516996487),
 (448, 0.0419960525565808),
 (449, 0.048795003647426664),
 (450, 0.022507456830317185),
 (451, 0.023531040266750586),
 (452, 0.027277236279499045),
 (453, 0.023002185311411807),
 (454, 0.11904761904761905),
 (455, 0.023262105259961773),
 (456, 0.06241877839323594),
 (457, 0.07412493166611012),
 (458, 0.06546536707079771),
 (459, 0.03217447260438935),
 (460, 0.023262105259961773),
 (461, 0.1683587574253685),
 (462, 0.0),
 (463, 0.03217447260438935),
 (464, 0.0),
 (465, 0.0),
 (466, 0.1690308509457033),
 (467, 0.08478078067985947),
 (468, 0.026082026547865053),
 (469, 0.06613000712661082),
 (470, 0.04364357804719848),
 (471, 0.07059312080025176),
 (472, 0.07142857142857144),
 (473, 0.0839921051131616),
 (474, 0.0),
 (475, 0.06131393394849658),
 (476, 0.0890870806374748),
 (477, 0.0),
 (478, 0.036624877106575575),
 (479, 0.0890870806374748),
 (480, 0.04819626927118799),
 (481, 0.0),
 (482, 0.026462806201248155),
 (483, 0.10432810619146021),
 (484, 0.0563436169819011),
 (485, 0.04941662111074008),
 (486, 0.05572782125753528),
 (487, 0.12598815766974242),
 (488, 0.06774797209007694),
 (489, 0.0),
 (490, 0.1315903389919538),
 (491, 0.08247860988423225),
 (492, 0.05832118435198043),
 (493, 0.018059841095769247),
 (494, 0.0),
 (495, 0.1930468356263361),
 (496, 0.019756519492339992),
 (497, 0.0),
 (498, 0.0643489452087787),
 (499, 0.0),
 (500, 0.023002185311411807),
 (501, 0.07715167498104596),
 (502, 0.14458880781356395),
 (503, 0.07229440390678199),
 (504, 0.0),
 (505, 0.12344267996967354),
 (506, 0.02817180849095055),
 (507, 0.21912524504463887),
 (508, 0.09100315103865801),
 (509, 0.022043335708870272),
 (510, 0.09412416106700235),
 (511, 0.08058229640253804),
 (512, 0.05730682550612528),
 (513, 0.09639253854237598),
 (514, 0.04819626927118799),
 (515, 0.022507456830317185),
 (516, 0.021398024625545648),
 (517, 0.0),
 (518, 0.04819626927118799),
 (519, 0.0),
 (520, 0.0),
 (521, 0.052164053095730106),
 (522, 0.0),
 (523, 0.046524210519923545),
 (524, 0.0),
 (525, 0.021606790785072143),
 (526, 0.0),
 (527, 0.0),
 (528, 0.022271770159368702),
 (529, 0.09200874124564723),
 (530, 0.07938841860374446),
 (531, 0.046524210519923545),
 (532, 0.021606790785072143),
 (533, 0.05832118435198043),
 (534, 0.06900655593423542),
 (535, 0.09759000729485333),
 (536, 0.06900655593423542),
 (537, 0.06172133998483677),
 (538, 0.0),
 (539, 0.2252817784447915),
 (540, 0.045501575519329006),
 (541, 0.06185895741317419),
 (542, 0.037151880838356854),
 (543, 0.07142857142857144),
 (544, 0.10585122480499262),
 (545, 0.024098134635593994),
 (546, 0.059391387091649865),
 (547, 0.07319250547113999),
 (548, 0.0),
 (549, 0.11253728415158593),
 (550, 0.023531040266750586),
 (551, 0.06419407387663695),
 (552, 0.0),
 (553, 0.02686076546751268),
 (554, 0.0),
 (555, 0.041403933560541256),
 (556, 0.02380952380952381),
 (557, 0.12515654358043973),
 (558, 0.0),
 (559, 0.026462806201248155),
 (560, 0.04087595596566439),
 (561, 0.030860669992418384),
 (562, 0.027277236279499045),
 (563, 0.024098134635593994),
 (564, 0.08748177652797065),
 (565, 0.04087595596566439),
 (566, 0.018712029714127994),
 (567, 0.02470831055537004),
 (568, 0.12858612496840993),
 (569, 0.020619652471058063),
 (570, 0.059391387091649865),
 (571, 0.018712029714127994),
 (572, 0.07655590023509529),
 (573, 0.019596545041740514),
 (574, 0.042796049251091296),
 (575, 0.04761904761904762),
 (576, 0.024397501823713332),
 (577, 0.13231403100624078),
 (578, 0.041239304942116126),
 (579, 0.10146925788636821),
 (580, 0.021398024625545648),
 (581, 0.157485197087178),
 (582, 0.23097828906119441),
 (583, 0.044543540318737404),
 (584, 0.0363696483726654),
 (585, 0.0),
 (586, 0.06185895741317419),
 (587, 0.07509392614826384),
 (588, 0.024397501823713332),
 (589, 0.08642716314028857),
 (590, 0.030860669992418384),
 (591, 0.06419407387663695),
 (592, 0.025031308716087945),
 (593, 0.0),
 (594, 0.04941662111074008),
 (595, 0.1235415527768502),
 (596, 0.08728715609439695),
 (597, 0.04941662111074008),
 (598, 0.05542739954736933),
 (599, 0.04826170890658402),
 (600, 0.06546536707079771),
 (601, 0.03289758474798845),
 (602, 0.04087595596566439),
 (603, 0.05143444998736397),
 (604, 0.05730682550612528),
 (605, 0.0),
 (606, 0.0),
 (607, 0.08478078067985947),
 (608, 0.0),
 (609, 0.041612518928823956),
 (610, 0.05381220025006315),
 (611, 0.02119519516996487),
 (612, 0.08322503785764791),
 (613, 0.033671751485073696),
 (614, 0.05143444998736397),
 (615, 0.02865341275306264),
 (616, 0.026082026547865053),
 (617, 0.05143444998736397),
 (618, 0.08175191193132877),
 (619, 0.0),
 (620, 0.0),
 (621, 0.059391387091649865),
 (622, 0.04239039033992974),
 (623, 0.0),
 (624, 0.09449111825230681),
 (625, 0.029160592175990215),
 (626, 0.07059312080025176),
 (627, 0.10350983390135313),
 (628, 0.06482037235521643),
 (629, 0.04364357804719848),
 (630, 0.02119519516996487),
 (631, 0.02380952380952381),
 (632, 0.07319250547113999),
 (633, 0.018993429409939658),
 (634, 0.07715167498104596),
 (635, 0.06613000712661082),
 (636, 0.025367314471592052),
 (637, 0.045501575519329006),
 (638, 0.029160592175990215),
 (639, 0.0),
 (640, 0.04819626927118799),
 (641, 0.0),
 (642, 0.0),
 (643, 0.08908708063747481),
 (644, 0.05143444998736397),
 (645, 0.0419960525565808),
 (646, 0.048795003647426664),
 (647, 0.04364357804719848),
 (648, 0.02817180849095055),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.026462806201248155),
 (653, 0.10350983390135313),
 (654, 0.07715167498104596),
 (655, 0.024397501823713332),
 (656, 0.0),
 (657, 0.06734350297014739),
 (658, 0.04761904761904762),
 (659, 0.02380952380952381),
 (660, 0.09449111825230681),
 (661, 0.15194743527951726),
 (662, 0.0),
 (663, 0.0),
 (664, 0.05455447255899809),
 (665, 0.06900655593423542),
 (666, 0.04819626927118799),
 (667, 0.0),
 (668, 0.06172133998483677),
 (669, 0.025717224993681984),
 (670, 0.015058465048420856),
 (671, 0.06900655593423542),
 (672, 0.04941662111074008),
 (673, 0.01928791874526149),
 (674, 0.06482037235521643),
 (675, 0.044086671417740544),
 (676, 0.027277236279499045),
 (677, 0.024098134635593994),
 (678, 0.0563436169819011),
 (679, 0.0),
 (680, 0.07610194341477616),
 (681, 0.030261376633440123),
 (682, 0.021398024625545648),
 (683, 0.044086671417740544),
 (684, 0.0),
 (685, 0.027713699773684666),
 (686, 0.0),
 (687, 0.12858612496840993),
 (688, 0.044543540318737404),
 (689, 0.0),
 (690, 0.023531040266750586),
 (691, 0.08058229640253804),
 (692, 0.10130511230913847),
 (693, 0.0),
 (694, 0.020088585092257697),
 (695, 0.05730682550612528),
 (696, 0.0),
 (697, 0.0),
 (698, 0.020261022461827694),
 (699, 0.0),
 (700, 0.025031308716087945),
 (701, 0.0657951694959769),
 (702, 0.021398024625545648),
 (703, 0.01928791874526149),
 (704, 0.06299407883487121),
 (705, 0.022750787759664503),
 (706, 0.023262105259961773),
 (707, 0.027713699773684666),
 (708, 0.045501575519329006),
 (709, 0.0),
 (710, 0.0419960525565808),
 (711, 0.05292561240249631),
 (712, 0.0),
 (713, 0.023531040266750586),
 (714, 0.0),
 (715, 0.09078412990032037),
 (716, 0.030261376633440123),
 (717, 0.0),
 (718, 0.04239039033992974),
 (719, 0.0),
 (720, 0.024397501823713332),
 (721, 0.02865341275306264),
 (722, 0.0),
 (723, 0.02380952380952381),
 (724, 0.023002185311411807),
 (725, 0.0),
 (726, 0.0),
 (727, 0.032712244767539374),
 (728, 0.0682523632789935),
 (729, 0.0),
 (730, 0.03327791628198609),
 (731, 0.04706208053350117),
 (732, 0.06900655593423542),
 (733, 0.04087595596566439),
 (734, 0.06241877839323594),
 (735, 0.046524210519923545),
 (736, 0.030261376633440123),
 (737, 0.06613000712661082),
 (738, 0.0),
 (739, 0.030261376633440123),
 (740, 0.11253728415158593),
 (741, 0.05006261743217589),
 (742, 0.02817180849095055),
 (743, 0.022750787759664503),
 (744, 0.04941662111074008),

In [57]:
def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [58]:
recommend('Avatar')

Lifeforce
Aliens vs Predator: Requiem
Battle: Los Angeles
Titan A.E.
Independence Day

In [59]:
new.iloc[1216].title

'Aliens vs Predator: Requiem'

In [60]:
import pickle

In [61]:
pickle.dump(new,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))